name: dvm
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  path: ^1.8.3
  file_copy: ^1.0.7
  cli_progress_bar: ^1.0.4
  rxdart: ^0.27.7
  dart_console: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dvm: dvm
